### ISSUE TITLE
Remote Project Move Resource

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/faircopy#414]
You can now (once again) move resources between TEI Documents and in and out of TEI Documents. This now works both in remote and offline projects. This Move Resource function is accessed via the actions button after selecting one or more resources from the Resource Browser.

**Comment by SteveMarvin** [comment]
I can't seem to find the Move action.

**Comment by NickLaiacona** [comment]
I'm wondering if this is related to the permissions issue you were having earlier. Both the source and destination need to be checked out (unless the target is the root dir)
