### ISSUE TITLE
Restart to update doesn't restart

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/faircopy#452]
When I see an update available, I click update, and it appears to download the update.

But clicking "restart to update", FC never restarts.

Update: 

I also still see the "Update" available after manual restart, post-update:

<img width="436" alt="Screen Shot 2022-10-12 at 17 02 06" src="https://user-images.githubusercontent.com/882377/195447239-ef0005a3-e3cc-4683-904c-038727a26762.png">

**Comment by NickLaiacona** [comment]
As of v1.2.0, we no longer autoupdate the software
