### ISSUE TITLE
Sometimes, structure tree disappears when switching views.

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/faircopy#491]

**Comment by SteveMarvin** [comment]
Unable to reproduce this.

**Comment by NickLaiacona** [comment]
Sorry, meant to add some testing notes here... if you open a 2 longish docs in dev 14, then resize the window and switch between them, you can see this happen. Shouldn't happen in dev 15.

**Comment by SteveMarvin** [comment]
Aha, that's good intel! However, I am still seeing no issues with the tree. I can see it refresh after the resize, and it comes back solid. 👍

**Comment by NickLaiacona** [comment]
yeah, it can be hard to reproduce
