### ISSUE TITLE
Add attribute to schema button missing

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/faircopy#504]
I have the config checked out, I have the resource checked out. I am admin admin, so I have all permissions. Why am I not seeing the "Add to schema" button?
![image.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/4a8c31ff-ab7a-4e20-8948-e4cdde50cf88)

I am seeing the add button for elements, but not to add attributes to marks

![image.png](https://images.zenhubusercontent.com/570d1074bf93871ccd994cd2/d62a1728-54c0-4b51-b437-d45c9879d8dc)

**Comment by NickLaiacona** [comment]
Same as #294
