### ISSUE TITLE
Move Surfaces between Facs

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/faircopy#518]
You can now move images (surfaces) between facimile resources, in a similar manner to how you can move resources between documents. This functionality is accessible via the actions dialog when looking at the list of surfaces in a given facs.

**Comment by SteveMarvin** [comment]
This is confusing. I can move things, but it's not clear where they are going, and they end up in a strange place.

I try to move an image out of a resource
![image](https://github.com/performant-software/faircopy/assets/18423533/0d4bf728-9558-4231-a981-7957a2b52ab8)

All of the possible destinations look alike:
![image](https://github.com/performant-software/faircopy/assets/18423533/589529c5-375f-4bb8-98e9-8714368f0ee7)


And they always end up in the same place, which I did not know I was selecting:
![image](https://github.com/performant-software/faircopy/assets/18423533/0d98e94f-c937-4e9d-ad7b-923c4788ba78)

**Comment by NickLaiacona** [comment]
OK, the reason they all look alike is because this was a server where we ran a workshop in which all the participants were using the same example file as a starting point. The facs listing on the move dialog are only the ones you have checked out, so if you have a bunch of facs with the same name, you could just check out the two you want to move things between. 

I think we do need to communicate to the user somehow that this list is only checked out resources.
