### ISSUE TITLE
Add To Schema button not always appearing

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/faircopy#556]
When I have elements not in the project schema, sometimes I get the Add To Schema button and sometimes I do not

<img width="1880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE95QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c50042fd5e2d9d06818359bc0d32f38b86bdd7b/image.png" alt="image.png" />

**Comment by NickLaiacona** [comment]
This is the same issue as #294
